BEGIN
  for cur in (SELECT cs.CONSTRAINT_NAME FROM USER_CONSTRAINTS cs
  JOIN user_cons_columns cc ON cs.CONSTRAINT_NAME  = cc.CONSTRAINT_NAME
  WHERE cs.TABLE_NAME  = 'ACCOUNT_LOGS' AND cs.CONSTRAINT_TYPE = 'R' and cc.column_name = 'TASK_ID')
  LOOP
    execute immediate ('ALTER TABLE ACCOUNT_LOGS DROP CONSTRAINTS ' || cur.CONSTRAINT_NAME);
  end loop;
end;
/

ALTER TABLE ACCOUNT_LOGS
ADD CONSTRAINT ACCOUNT_LOGS_TASK_ID
FOREIGN KEY (TASK_ID) REFERENCES TASKS(ID);
/