CREATE USER task_tracker IDENTIFIED BY qwerty;
GRANT CONNECT, CREATE ANY TABLE, CREATE ANY SEQUENCE TO task_tracker;

CREATE USER auth IDENTIFIED BY qwerty;
GRANT CONNECT, CREATE ANY TABLE, CREATE ANY SEQUENCE TO auth;